printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
svelteSortOrder: options-scripts-markup-styles
svelteStrictMode: true
svelteBracketNewLine: true
svelteAllowShorthand: false
svelteIndentScriptAndStyle: false
