printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
svelteSortOrder: options-styles-scripts-markup
svelteStrictMode: true
svelteBracketNewLine: false
svelteAllowShorthand: false
svelteIndentScriptAndStyle: false
